= Repo demonstrating Transactional issue in Graisl 4.1.4 Integration tests
// see: https://asciidoctor.org/docs/user-manual/#table-of-contents-summary
:toc-title: Table of Contents
// how many headline levels to display in table of contents?
:toclevels: 4
// https://asciidoctor.org/docs/user-manual/#sections-summary
// turn numbering on or off (:sectnums!:)
:sectnums:
// enumerate how many section levels?
:sectnumlevels: 2
// show anchors when hovering over section headers
:sectanchors:
// render section headings as self referencing links
:sectlinks:
// number parts of a book
:partnums:
:icons: font

== Introduction

This is a simple repo to demonstrate a transactional issue in Grails 4.1.4 integration tests.

The integration test aims to update an existing Book object by calling a transactional service, which in turn calls a GORM Data service to update the Book.


I have created 3 different Spec methods that demonstrate the odd behavior.

The preamble of the integration tests is a follows:

[source,groovy]
.BookServiceIntSpec.groovy
----
import acme.domain.Book
import grails.gorm.transactions.Rollback
import grails.testing.mixin.integration.Integration
import spock.lang.Specification
import spock.lang.Subject

@Integration
@Rollback
@Subject(BookService)
class BookServiceIntSpec extends Specification {

    BookService bookService

    Book book

    private void setup() {
        book = new Book(title: "The Hobbit")
        book.save(flush: true, failOnError: true)
    }
}
----



== Test cases

=== It is able to update a Book without creating a new transaction, by using GORM in the service


[source,groovy]
.Production code in BookService
----
ifndef::env-github[]
include::grails-app/services/acme/library/BookService.groovy[tag=updateWithGORM]
endif::[]
ifdef::env-github[]
    Book updateWithGORM(Book toUpdate) {
        toUpdate.save(flush: true, failOnError: true)
    }
endif::[]
----

This is the Integration test:

[source,groovy]
.It is able to update a Book without creating a new transaction, by using GORM in the service.
----
ifndef::env-github[]
include::src/integration-test/groovy/acme/library/BookServiceIntSpec.groovy[tag=updateWithGORM]
endif::[]
ifdef::env-github[]
    def "It is able to update a Book without creating a new transaction, by using GORM in the service."() {
        when:
        book.title = updatedTitle
        bookService.updateWithGORM(book)

        then:
        Book.findByTitle(updatedTitle) != null

        where:
        updatedTitle = "Bilbo The Hobbit"
    }
endif::[]
----


=== It is NOT able to update a Book without creating a new transaction, if using a Data Service

[source,groovy]
.Production code in BookService
----
ifndef::env-github[]
include::grails-app/services/acme/library/BookService.groovy[tag=updateWithDataService]
endif::[]
ifdef::env-github[]
    Book updateWithDataService(Book toUpdate) {
        bookDataService.save(toUpdate)
    }
endif::[]
----

This is the Integration test:

[source,groovy]
.It is able to update a Book without creating a new transaction, by using GORM in the service.
----
ifndef::env-github[]
include::src/integration-test/groovy/acme/library/BookServiceIntSpec.groovy[tag=updateWithDataService]
endif::[]
ifdef::env-github[]
    def "It is NOT able to update a Book without creating a new transaction, if using a Data Service."() {
        when:
        book.title = updatedTitle
        bookService.updateWithDataService(book)

        then:
        Book.findByTitle(updatedTitle) == null //<1>

        where:
        updatedTitle = "Bilbo The Hobbit"
    }
endif::[]
----
<1> The updated book cannot be found after requesting an update

=== It is able to update a Book by creating a new transaction, if using a Data Service

[source,groovy]
.Production code in BookService
----
ifndef::env-github[]
include::grails-app/services/acme/library/BookService.groovy[tag=updateWithDataService]
endif::[]
ifdef::env-github[]
    Book updateWithDataService(Book toUpdate) {
        bookDataService.save(toUpdate)
    }
endif::[]
----

This is the Integration test:

[source,groovy]
.It is able to update a Book without creating a new transaction, by using GORM in the service.
----
ifndef::env-github[]
include::src/integration-test/groovy/acme/library/BookServiceIntSpec.groovy[tag=updateWithDataServiceAndNewTransaction]
endif::[]
ifdef::env-github[]
    def "It is able to update a Book by creating a new transaction, if using a Data Service."() {
        when:
        book.title = updatedTitle
        Book.withNewTransaction { //<1>
            bookService.updateWithDataService(book)
        }

        then:
        Book.findByTitle(updatedTitle) != null //<2>

        where:
        updatedTitle = "Bilbo The Hobbit"
    }
endif::[]
----
<1> By usign withNewTransaction, the update succeeds
<2> The updated book CAN be found after requesting an update

== Conclusion

Either this is a bug in the integration test runtime of Grails 4.1.4 or the documentation is not clear on how to use transactional services in integration tests.