= Repo demonstrating Transactional issue in Graisl 4.1.4 Integration tests
// see: https://asciidoctor.org/docs/user-manual/#table-of-contents-summary
:toc-title: Table of Contents
// how many headline levels to display in table of contents?
:toclevels: 4
// https://asciidoctor.org/docs/user-manual/#sections-summary
// turn numbering on or off (:sectnums!:)
:sectnums:
// enumerate how many section levels?
:sectnumlevels: 2
// show anchors when hovering over section headers
:sectanchors:
// render section headings as self referencing links
:sectlinks:
// number parts of a book
:partnums:
:icons: font

== Introduction

This is a simple repo to demonstrate a transactional issue in Grails 4.1.4 integration tests.

The integration test aims to update an existing Book object by calling a transactional service, which in turn calls a GORM Data service to update the Book.


I have created 3 different Spec methods that demonstrate the odd behavior.

== Test cases

=== It is able to update a Book without creating a new transaction, by using GORM in the service

[source,groovy]
.Production code in BookService
----
include::grails-app/services/acme/library/BookService.groovy[tag=updateWithGORM]
----

This is the Integration test:

[source,groovy]
.It is able to update a Book without creating a new transaction, by using GORM in the service.
----
include::src/integration-test/groovy/acme/library/BookServiceIntSpec.groovy[tag=updateWithGORM]
----


=== It is NOT able to update a Book without creating a new transaction, if using a Data Service

[source,groovy]
.Production code in BookService
----
include::grails-app/services/acme/library/BookService.groovy[tag=updateWithDataService]
----

This is the Integration test:

[source,groovy]
.It is able to update a Book without creating a new transaction, by using GORM in the service.
----
include::src/integration-test/groovy/acme/library/BookServiceIntSpec.groovy[tag=updateWithDataService]
----
<1> The updated book cannot be found after requesting an update

=== It is able to update a Book by creating a new transaction, if using a Data Service

[source,groovy]
.Production code in BookService
----
include::grails-app/services/acme/library/BookService.groovy[tag=updateWithDataService]
----

This is the Integration test:

[source,groovy]
.It is able to update a Book without creating a new transaction, by using GORM in the service.
----
include::src/integration-test/groovy/acme/library/BookServiceIntSpec.groovy[tag=updateWithDataServiceAndNewTransaction]
----
<1> By usign withNewTransaction, the update succeeds
<2> The updated book CAN be found after requesting an update

